### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by masihyeganeh** [getinsomnia/go-srp#2]
Hi.
Thanks a lot for your implementation. It saved me hours.
I just made a [fork](https://github.com/masihyeganeh/go-srp) of it and made it compatible with Apple's CoreCrypto implementation or SRP.
Just wanted to know if you are OK if I make it public under my username in Github?
And also wanted to know if you will merge if I make a pull request of that or not. I think you won't because it is not compatible with `node-srp` anymore.
Regards

**Comment by gschier** [comment]
Ooo nice work! It doesn't look like it's that different but you're right, it would break compatibility with `node-srp`, which wouldn't be good.

I'm perfectly happy with you maintaining your own fork under your username. 

Thanks for asking! 😄 👋
